swagger: '2.0'
info:
  description: 'This is an eg. fields of BioSCOOP communication standard.'
  version: 0.0.1
  title: BioSCOOP
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: blazej.marciniak@biol.uni.lodz.pl
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: sample.biobank.pl
basePath: /v1
tags:
  - name: donor
    description: Donor description
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
schemes:
  - http
paths:
  /donor:
    post:
      tags:
        - donor
      description: Adding new donor
      operationId: addDonor
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: donor_description
          description: Donor data to store
          required: true
          schema:
            $ref: '#/definitions/Donor'
      responses:
        '404':
          description: Donor not found
definitions:
  Kind:
    description: 'human kind'
    type: object
    properties:
      basic:
        type: string
        enum:
          - 'white'
          - 'yellow'
          - 'black'
          - 'mixed'
  SkinTone:
    description: 'properties that describe skin tone'
    type: object
    properties:
      vonLuschan:
        description: 'von Luschan scale'
        type: integer
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
          - 24
          - 25
          - 26
          - 27
          - 28
          - 29
          - 30
          - 31
          - 32
      michalski:
        description: 'michalski scale'
        type: integer
        enum:
          - 10
          - 20
          - 30
          - 40
          - 50
          - 60
          - 70
          - 80
      timestamp:
        description: 'measurement date'
        type: object
        properties:
          year:
            type: integer
          month:
            type: integer
          day:
            type: integer
  HairColor:
    description: 'properties that describe Hair colour'
    type: object
    properties:
      hc_palet:
        type: integer
      text_description:
        type: string
        enum:
          - 'A very light blond'
          - 'B,C,D,E light blond'
          - 'F,G,H,I,J,K,L blond'
          - 'M,N,O dark blond'
          - 'P,Q,R,S,T light brown to medium brown'
          - 'U,V,W,X,Y dark brown/black'
          - '1,2,3,4 red'
          - '5,6 red blond'
      timestamp:
        description: 'measurement date'
        type: object
        properties:
          year:
            type: integer
          month:
            type: integer
          day:
            type: integer
  Donor:
    type: object
    required:
      - donorId
    properties:
      id:
        type: integer
        format: int64
      donorId:
        type: string
      gender:
        type: string
        description: Donor's gender
        enum:
          - Male
          - Female
          - Transgender
          - Other
      age:
        type: integer
        description: Donor's age based on date of birth
      kind:
        $ref: '#/definitions/Kind'
      skin_tone:
        $ref: '#/definitions/SkinTone'
      hair_color:
        $ref: '#/definitions/HairColor'
