swagger: '2.0'
info:
  description: This is an eg. fields of BioSCOOP communication standard.
  version: 0.0.1
  title: BioSCOOP
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: blazej.marciniak@biol.uni.lodz.pl
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: sample.biobank.pl
basePath: /v1
tags:
  - name: donor
    description: Donor description
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
schemes:
  - http
paths:
  /donor:
    post:
      tags:
        - donor
      description: Adding new donor
      operationId: addDonor
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: donorDescription
          description: Donor data to store
          required: true
          schema:
            $ref: '#/definitions/Donor'
      responses:
        '404':
          description: Donor not found
definitions:
  MeasurementDate:
    description: measurement date
    type: object
    properties:
      date:
        type: string
        format: date-time
      dateCorrectess:
        type: string
  Kind:
    description: human kind
    type: object
    properties:
      basic:
        type: string
        enum:
          - white
          - yellow
          - black
          - mixed
  SkinTone:
    description: properties that describe skin tone
    type: object
    properties:
      vonLuschan:
        description: von Luschan scale
        type: integer
        minimum: 1
        maximum: 32
      michalski:
        description: michalski scale
        type: integer
        enum:
          - 10
          - 20
          - 30
          - 40
          - 50
          - 60
          - 70
          - 80
      timestamp:
        $ref: '#/definitions/MeasurementDate'
  HairColor:
    description: properties that describe Hair colour
    type: object
    properties:
      hcPalet:
        type: integer
      textDescription:
        type: string
        enum:
          - 'A very light blond'
          - 'B,C,D,E light blond'
          - 'F,G,H,I,J,K,L blond'
          - 'M,N,O dark blond'
          - 'P,Q,R,S,T light brown to medium brown'
          - 'U,V,W,X,Y dark brown/black'
          - '1,2,3,4 red'
          - '5,6 red blond'
      timestamp:
        $ref: '#/definitions/MeasurementDate'
  Weight: 
    description: the body mass in kg
    type: object
    properties:
      weight:
        type: number
      timestamp:
        $ref: '#/definitions/MeasurementDate'
  Height:
    description: the body height in cm
    type: object
    properties:
      height:
        type: number
      timestamp:
        $ref: '#/definitions/MeasurementDate'
  EyeColour:
    description: eye colour
    type: object
    properties:
      IrisPlex:
        type: integer
        minimum: 1
        maximum: 16
      textDescription:
        type: string
        enum: 
          - '1-2 blue' 
          - '3 blue-gray'
          - '4 gray iris'
          - '5 blue-gray iris with yellow/brown spots' 
          - '6 gray green iris with yellow/brown spots'
          - '7 green'
          - '8 green with yellow/brown spots'
          - '9-10-11 light brown or hazel'
          - '12-13 medium brown'
          - '14-15-16 dark brown or black'
  WHR:
    description: waist - hip ratio
    type: object
    properties:
      WHR: 
        type: number
      timestamp:
        $ref: '#/definitions/MeasurementDate'
  BMI:
    description: body mass index
    type: object
    properties:
      BMI: 
        type: number
      timestamp:
        $ref: '#/definitions/MeasurementDate'
  BloodGroup:
    description: blood group
    type: object
    properties:
      ABO: 
        type: string
        enum: 
          - 'A'
          - 'B'
          - 'AB'
          - '0'
      Rh:
        type: string
        enum:
          - 'Rh+'
          - 'Rh-'
      Lewis:
        type: string
        enum:
          - 'Le(a-b-)'
          - 'Le(a-b+)'
          - 'Le(a+b-)'
      Kell:
        type: string
        enum:
          - 'K'
          - 'k'
          - 'kp'
      Other: 
        type: string
  MedicalProcedure:
    description: medical procedure
    type: object
    properties:
      icd9:
        type: string
        pattern: '([V\d]\d{2}(\.?\d{0,2})?|E\d{3}(\.?\d)?|\d{2}(\.?\d{0,2})?)'
      noCode:
        type: string
      timestamp:
        $ref: '#/definitions/MeasurementDate'
  Disease:
    description: Disease
    type: object
    properties:
      icd-9:
        type: string
        pattern: '([V\d]\d{2}(\.?\d{0,2})?|E\d{3}(\.?\d)?|\d{2}(\.?\d{0,2})?)'
      icd-10:
        type: string
        pattern: '([A-TV-Z][0-9][A-Z0-9](\.?[A-Z0-9]{0,4})?)'
      noCode:
        type: string
      timestamp:
        $ref: '#/definitions/MeasurementDate'
  SampleMaterial:
    description: sample material
    type: object
    properties:
      materialType:
        type: string
        enum:
        - 'DNA'
        - 'RNA'
        - 'cDNA/mRNA'
        - 'microRNA'
        - 'Whole blood'
        - 'Peripheral blood cells'
        - 'Plasma'
        - 'Serum'
        - 'Tissue, cryo preserved'
        - 'Tissue, paraffin preserved'
        - 'Cell lines'
        - 'Urine'
        - 'Saliva'
        - 'Faeces'
        - 'Pathogen'
        - 'Other'
      storageTemperature:
        type: string
        description: values in Celsius degrees scale
        enum:
        - 'Room temperature'
        - '2 to 10'
        - '-18 to -35'
        - '-60 to -85'
        - '-150 to -196'
        - 'other'
  Donor:
    type: object
    required:
      - donorId
    properties:
      id:
        type: integer
        format: int64
      donorId:
        type: string
      gender:
        type: string
        description: Donor's gender
        enum:
          - Male
          - Female
          - Transgender
          - Other
      age:
        type: integer
        description: Donor's age based on date of birth
      kind:
        $ref: '#/definitions/Kind'
      skinTone:
        $ref: '#/definitions/SkinTone'
      hairColor:
        $ref: '#/definitions/HairColor'
      weight:
        $ref: '#/definitions/Weight'
      height:
        $ref: '#/definitions/Height'
      eyeColor:
        $ref: '#/definitions/EyeColour'
      whr:
        $ref: '#/definitions/WHR'
      bmi:
        $ref: '#/definitions/BMI'
      blood group:
        $ref: '#/definitions/BloodGroup'
      diseases:
        type: array
        items:
          $ref: '#/definitions/Disease'
      medicalProcedures:
        type: array
        items:
          $ref: '#/definitions/MedicalProcedure'
      sampleMaterial:
          $ref: '#/definitions/SampleMaterial'
